---
title: "The German debt brake is stupid!"
date: 2025-03-02
date-modified: 2025-03-02
original-url: "https://addxorrol.blogspot.com/2025/03/the-german-debt-brake-is-stupid.html"
blogger-id: "3673954472153580613"
---
Welcome to one of my political posts. This blog post should rightfully be titled "the German debt brake is stupid, and if you support it, so are you (at least in the domain of economics)". Given that a nontrivial number of Germans agree with the debt brake, and given that there is a limit on the sensible number of characters in the title, I chose a shorter title - for brevity and to reduce offense. I nonetheless think that support for the debt brake, and supporters of the debt brake, are stupid.  
  
In the following, I will list the reasons why I think the debt brake is stupid, and talk about a few arguments I have heard in favor of the debt brake, and why I don't buy any of them.  
  
**Reason 1: The debt brake is uniquely German, and I think the odds that Germany has somehow uncovered a deeper economic truth than anyone else is not high.**

If you engage with economists a bit, you'll hear non-German economists make statements such as "there is economics, and there is German economics, and they have little in common" or "the problem with German economics is that it's really a branch of moral philosophy and not an empirical science". Pretty much the entire world stares in bewilderment at the debt brake law, and I have yet to find a non-German economist of any repute that says the German debt brake is a sensible construct.  
  
The [Wikipedia page](https://en.wikipedia.org/wiki/German_balanced_budget_amendment) is pretty blatant in showing that pretty much the only group supporting the debt brake are ... 48% of a sample of 187 German university professors for economics, in a poll conducted by an economic research think tank historically associated with the debt brake.  
  
Now, I am not generally someone that blindly advocates for going with the mainstream majority opinion, but if the path you have chosen is described by pretty much the entire world as bizarre, unempirical, and based on moral vs. scientific judgement, one should possibly interrogate one's beliefs carefully.  
  
If the German debt brake is a sensible construct, then pretty much every other country in the world is wrong by not having it, and the German government has enacted something unique that should convey a tangible advantage. It should also lead to other countries looking at these advantages and thinking about enacting their own, similar, legislation.  
  
The closest equivalent to the German debt brake is the Swiss debt brake - but Switzerland has a lot of basis-democratic institutions that allow a democratic majority to change the constitution; in particular, a simple double-majority - majority of voters in the majority of cantons - is sufficient to remove the debt brake again. Switzerland can still act in times of crisis provided most voters in most cantons want to.  
  
Germany, with the 2/3rds parliamentary majority required for a constitutional change, cannot. As such, the German debt brake is the most stringent and least flexible such rule in the world.  
  
I don't see any evidence that the debt brake is providing any benefits to either Germans or the world. I see no other country itching to implement a similarly harsh law. Do we really believe that Germany has uncovered a deeper economic truth nobody else can see?  

**Reason 2: The debt brake is anti-market, and prevents a mutually beneficial market activity**

While I am politically center-left, I am fiercely pro-market. I think markets are splendid allocation instruments, decentralized decision-making systems, information processors, and by-and-large the primary reason why the West out-competed the USSR when it came to producing goods. Markets allow the many actors in the economy to find ways how they can obtain mutual advantage by trading with each other, and interfering with markets should be done carefully, usually to correct some form of severe market failure (natural monopolies, tragedy-of-the-common, market for lemons etc. -- these are well-documented).  
  
The market for government debt is a market like any other. Investors that believe that the government provides the best risk-adjusted return when compared to all other investment opportunities wish to lend the government money to invest it and provide the return. The government pays interest rate to these investors, based on the risk-free rate plus a risk premium.  
  
Capital markets exist in order to facilitate decentralized resource allocation. If investors think that the best risk-adjusted returns are to be had by loaning the government money to invest in infrastructure or spend on other things, they should be allowed to offer lower and lower risk premia.  
  
The debt brake interferes in this market by artificially constraining the government demand for debt. Even if investors were willing to pay the German government money to please please invest it in the broader economy, the German government wouldn't be allowed to do it.  
  
In some sense, this is a deep intervention in the natural signaling of debt markets, and the flow of goods. It is unclear what market failure is being addressed here. 

**Reason 3: The debt brake prevents investments with positive expected value**

Assuming an opportunity arises where the government can invest sensibly in basic research or other infrastructure investments with strongly positive expected value for GDP growth and hence governmental income. Why should an arbitrary debt brake prohibit investments that are going to be net good for the whole of society?

**Reason 4: The debt brake is partially responsible for the poor handling of the migration spike in 2015**

Former Chancellor Merkel is often criticised for her "Wir schaffen das" ("We can do it") during the 2015 migration crisis. My main criticism, [even back then](https://x.com/halvarflake/status/649884887521067008), was that a sudden influx of young refugees has the potential for providing a demographic dividend, \*provided\* one manages to integrate the refugees into the society, the work force, and the greater economy rapidly. This necessitates investment, though: German language lessons, housing in economically non-deprived areas, German culture lessons, and much more -- and that sticking to the debt brake in an exceptional situation such as the 2015 migrant crisis is a terrible idea, because a sudden influx of refugees can have a destabilizing and economically harmful effect if the integration is botched. Successfully integrated people pay taxes and strengthen society, failure of integration leads to unemployment, potentially crime, and social disorder.  
  
My view is that Merkel dropped the entire weight of the integration work on German civil society (which performed as best as they could, and admirably) because she was entirely committed to a stupid and arbitrary rule. I also ascribe some of the strength of Germany's far right on the disappointment that came from this mishandling of a crisis-that-was-also-an-opportunity.  

**Reason 5: The debt brake is based on numbers that economists agree are near-impossible to estimate correctly**

It is extremely challenging to estimate the "[structural deficit](https://en.wikipedia.org/wiki/Deficit_spending#Structural_and_cyclical_deficit)" of a given government, and most economists agree that there's no proper objective measurement of it, particularly when not done in retrospect. A law that prohibits governments from acting based on an unknowable quantity appears to be a bad law to me.  
  
**Reason 6: The debt brake is fundamentally based on a fear that politicians act too much in their own interest - but does not provide a democratic remedy**

**  **

The underlying assumption of the debt brake is that politicians will act with their own best interest in mind, running long-term structural deficits that eventually bankrupt a country. In some sense, the notion is that "elected representatives cannot be trusted to handle the purse string, because they will use it to bribe the electorate to re-elect them".  
  
We can discuss the extent to which this is true, but in the end a democracy should adhere to the sovereign, which is the voters. If we are afraid of a political caste abusing their position as representatives to pilfer the public's coffers, we should give the public more direct voting rights in budgetary matters, not artificially constrain what may be legitimate and good investments.  
  
There is a deep anti-democratic undercurrent in the debt brake discussion: Either that the politicians cannot be trusted to behave in a fiscally responsible manner, or that the voters cannot be trusted to behave in a fiscally responsible manner, or that the view of politicians, voters and markets about what constitutes fiscal responsibility are somehow incorrect.  
  
**Reason 7: A German debt brake would be terrible policies for any business, why is it a good idea for a country?**

**  **

Imagine for a second a company would pass bylaws that prevent issuing any additional debt, only to be bypassable by a shareholder meeting where 2/3rds of all shareholders agree that the debt can be issued. This would essentially give minority shareholders a fantastic way of taking the company hostage and demand concessions because **taking on debt is a standard part of doing business**. If we don't think that a majority of elected politicians can be trusted to not abuse the purse strings to extract benefits for themselves, why do we think it's a good idea to give a smaller group of elected politicians the right to block the governments ability to react in a crisis?  
  
**Reason 8: A lot of debt-brake advocacy is based in the theory of "starving the beast"**

  
Debt-brake advocates are often simultaneous advocates of lower taxes. The theory is that by lowering taxes (and hence revenues) while creating a hard fiscal wall (the debt brake) one can force the government to cut popular programs to shrink the government - in other situations, cutting popular programs would be difficult as voters would not support it.  
  
This idea was called "[starving the beast](https://en.wikipedia.org/wiki/Starve_the_beast)" among US conservatives in the past. There's plenty of criticism of the approach, and all empirical evidence points to it being a terrible idea. It's undemocratic, too, as one is trying to create a situation of crisis to achieve a goal that would - assuming no crisis and democracy - not achievable.  
  
**Reason 9: Germany has let it's infrastructure decay to a point where the association of German industry is begging for infrastructure investments**

  

The BDI is hardly a left-leaning tax-and-spend-happy group. They're historically very conservative, anti-union etc. - yet in recent years the decay of German infrastructure, from roads to bridges to the train system, has sufficiently unsettled them that we now have an alliance of German Unions and the German Employer Association call for much-needed infrastructure investments and modernisation.  
  
The empirical evidence seems to be "when presented with a debt brake, politicians make necessary investments, and instead prefer to hollow out existing infrastructure".

  
**Reason 10: Europe needs rearmament now, which requires long-time commitments to defense spending, but also investment in R&D etc.  **
  
The post-1945 rules-based order has been dying, first slowly in the GWOT, then it convulsed with the first Trump term; it looked like it might survive when Biden got elected, but with the second Trump term it is clear that it is dead. Europeans have for 20 years ignored that this is coming, in spite of everybody that made regular trips to Washington DC having seen it. The debt brake now risks paralyzing the biggest Eurozone economy by handing control over increased defense spending to radical fringe parties that are financed and supported by hostile adversaries.  
  
Imagine a German parliament where the AfD and BSW jointly hold 1/3rd of the seats, and a war breaks out. Do we really want an adversary to be able to decide how much debt we can issue for national defense?  
  
**But the debt brake reassures investors and hence drives down Germany's interest rate payments!**  
  
Now, this is probably the only argument I have heard in favor of the debt brake that may merit some deeper discussion or investigation. There is an argument to be made that if investors perceive the risk of a default or the risk of inflation to be lower, they will demand a lesser coupon on the debt they provide. And I'm willing to entertain that thought. Something either I or someone that reads it should do is:  
  
1. Calculate the risk premium that Germany had to pay over the risk-free rate in the past.  
2. Observe to what extent the introduction of the debt brake, or the introduction of the COVID spending bills etc. impacted the spread between the risk-free rate and the yield on German government debt.  
  
There are some complications with this (some people argue that the yield on Bunds \*is\* the risk-free rate, or at least the closest approximation thereof), and one would still have to quantify what GDP shortfall was caused by excessive austerity, so the outcome of this would be a pretty broad spectrum of estimates. But I will concede that this is worth thinking about and investigating.  
  
At the same time, we are in a very special situation: The world order we all grew up in is largely over. The 1990s belief that we will all just trade, that big countries don't get to invade & pillage small countries, and that Europe can just disarm because the world is peaceful now is dead, and only a fool would cling to it.  
  
I know that people would like to see a more efficient administration, and a leaner budget. These are good goals, and should be pursued - but not by hemming in your own government to be unable to react to crises, be captured by an aggressive minority, and reduce democratic choice.  
  
Apologies for this rant, but given the fact that Europe has squandered the last 20 years, and that I perceive the German approach to debt and austerity to be a huge factor in this, it is hard for me to not show some of my frustration.
